zerochae/Altudy

BOJ/1406_에디터/juwon.java
BOJ/DataStructure_Go/Queue/Queue.go
BOJ/DataStructure_Go/Stack/stack.go

go stack, queue, BOJ-1406-java

go stack, queue, BOJ-1406-java

---

Programmers/주차 요금 계산/juwon.java

Modify: 주차 요금 계산

---

Programmers/최솟값 구하기/junstone.sql

Add: 최솟값 구하기

---

Programmers/주차 요금 계산/juwon.go

Add: 주차 요금 계산

---

Programmers/주차 요금 계산/youyeongjin.java

Add : 주차 요금 계산

---

.gitignore
BOJ/1021_회전하는 큐/juwon.java

Add: 1021 회전하는 큐

---

BOJ/1003_피보나치 함수/juwon.java
BOJ/1463_1로 만들기/juwon.java
BOJ/1932_정수 삼각형/juwon.java
BOJ/2839_설탕 배달/juwon.java

Add: Dynamic Programming

---

BOJ/2839_설탕 배달/juwon.go

Add: 2839 설탕 배달

---

BOJ/1463_1로 만들기/juwon.go

Add: 1463 1로 만들기

---

BOJ/1003_피보나치 함수/juwon.go

Add: 1003 피보나치 함수

---

BOJ/1406_에디터/juwon.go

Add: 1406 에디터

---

BOJ/10870_피보나치 수 5/juwon.go
BOJ/10870_피보나치 수 5/juwon.java

Add: 10870 피보나치 수 5

---

BOJ/2156_포도주 시식/juwon.go
BOJ/2156_포도주 시식/juwon.java
BOJ/9251_LCS/juwon.go
BOJ/9251_LCS/juwon.java

Add: 9251 LCS

---

Programmers/거리두기 확인하기/juwon.java

Add: 거리두기 확인하기

---

BOJ/9095_1+2+3 더하기/juwon.java

Add: 9095 1+2+3 더하기

---

BOJ/11726_2 x n 타일링/juwon.java

Add: 11726_ 2xN 타일링

---

BOJ/2178_미로 탐색/juwon.java

Add: 2178 미로 탐색

---

BOJ/2667_단지번호 붙이기/juwon.java

Add: 2667 단지번호 붙이기

---

BOJ/2606_바이러스/juwon.java

Add: 2606 바이러스

---

BOJ/14502_연구소/juwon.java

Add: 14502 연구소

---

BOJ/1697_숨바꼭질/juwon.java

Add: 1697 숨바꼭질

---

BOJ/10828_스택/juwon.js

Add: 10828 스택

---

BOJ/10845_큐/juwon.js

Add: 10845 큐

---

BOJ/10845_큐/juwon.js

Modify: 10845 큐

---

BOJ/1991_트리 순회/juwon.java

Add: 1991 트리 순회

---

BOJ/1068_트리/juwon.java

Add: 1068 트리

---

BOJ/2750_수 정렬하기/juwon.java

Add: 2750 수 정렬하기

---

Programmers/JadenCase 문자열 만들기/krungy.js

Add: JadenCase 문자열 만들기

---

Programmers/다리를 지나는 트럭/krungy.js

Add: 다리를 지나는 트럭

---

BOJ/1181_단어 정렬/juwon.java

Add: 1181 단어 정렬

---

Programmers/올바른 괄호/krungy.js
Programmers/핸드폰번호가리기/krungy.js

Add: 핸드폰번호가리기, 올바른 괄호

---

Programmers/나머지가 1이 되는 수 찾기/krungy.js
Programmers/내적/krungy.js

Add: 나머지가 1이 되는 수 찾기, 내적

---

Programmers/메뉴 리뉴얼/krungy.js

Add: 메뉴 리뉴얼

---

Programmers/124나라의숫자/krungy.js

Add: 124나라의숫자

---

Programmers/음양 더하기/juwon.js

Add: 음양 더하기

---

Programmers/없는숫자더하기/juwon.js

Add: 없는숫자더하기

---

Programmers/평균 구하기/juwon.js

Add: 평균 구하기

---

Programmers/두개뽑아서더하기/juwon.js

Add: 두개 뽑아서 더하기

---

Programmers/피보나치 수/krungy.js
Programmers/하샤드 수/krungy.js

Add: 하샤드 수, 피보나치 수

---

Programmers/3진법 뒤집기/juwon.js

Add: 3진법 뒤집기

---

Programmers/약수의 개수와 덧셈/juwon.js

Add: 약수의 개수와 덧셈

---

Programmers/평균 구하기/krungy.js
Programmers/폰켓몬/krungy.js

Add: 평균 구하기, 폰켓몬

---

BOJ/2501_약수 구하기/krungy.js

Add: 2501 약수 구하기

---

Programmers/나머지가 1이 되는 수 찾기/juwon.js

Add: 나머지가 1이 되는 수 찾기

---

BOJ/11656_접미사 배열/juwon.js

Add: 11656 접미사 배열

---

BOJ/10818_최소, 최대/krungy.js
BOJ/2460_지능형 기차/krungy.js
BOJ/3460_이진수/krungy.js

Add: 2501 이진수, 10810 최소 최대, 2460 지능형 기차

Add: 2501 이진수, 10810 최소 최대, 2460 지능형 기차

---

Programmers/숫자 문자열과 영단어/juwon.js

Add: 숫자 문자열과 영단어

---

BOJ/10870_피보나치 수 5/krungy.js
BOJ/2309_일곱 난쟁이/krungy.js
BOJ/2609_최대공약수와 최소공배수/krungy.js

Add: 10870 피보나치 수 5, 2309 일곱 난쟁이, 2609 최대공약수와 최소공배수

Add: 10870 피보나치 수 5, 2309 일곱 난쟁이, 2609 최대공약수와 최소공배수

---

BOJ/10867_중복 빼고 정렬하기/juwon.js

Add: 10867 중복 빼고 정렬하기

---

BOJ/1292_쉽게 푸는 문제/krungy.js
BOJ/1978_소수 찾기/krungy.js
BOJ/2693_N번째 큰 수/krungy.js

Add: 2693 N번째 큰 수, 1978 소수 찾기, 1292 쉽게 푸는 문제

Add: 2693 N번째 큰 수, 1978 소수 찾기, 1292 쉽게 푸는 문제

---

BOJ/5576_콘테스트/juwon.js

Add: 5576 콘테스트

---

BOJ/5576_콘테스트/juwon.js

Modify: 5576 콘테스트

---

BOJ/2581_소수/krungy.js

Add: 2581 소수

---

Programmers/나누어 떨어지는 숫자 배열/juwon.js

Add: 나누어 떨어지는 숫자 배열

---

Programmers/나누어 떨어지는 숫자 배열/juwon.js

Modify: 나누어 떨어지는 숫자 배열

---

Programmers/가운데 글자 가져오기/krungy.js

Add: 가운데 글자 가져오기

---

Programmers/완주하지 못한 선수/juwon.js

Add: 완주하지 못한 선수

---

Programmers/가장 큰 수/krungy.js

Add: 가장 큰 수

---

Programmers/문자열내마음대로정렬하기/juwon.js

Add: 문자열 내 마음대로 정렬하기

---

Programmers/문자열내p와y의개수/juwon.js

Add: 문자열 내 p와 y의 개수

---

BOJ/16435_스네이크버드/juwon.js

Add: 16435 스네이크버드

---

Programmers/나누어 떨어지는 숫자 배열/krungy.js
Programmers/다음 큰 숫자/krungy.js

Modify: 나누어 떨어지는 숫자 배열, Add: 다음 큰 숫자

Modify: 나누어 떨어지는 숫자 배열, Add: 다음 큰 숫자

---

Programmers/두개뽑아서더하기/krungy.js

Add: 두개뽑아서더하기

---

BOJ/1300_K번째 수/juwon.js

Add: 1300 K번째 수

---

Programmers/두정수사이의합/krungy.js
Programmers/로또최고순위최저순위/krungy.js

Add: 두정수사이의합, 로또의최고순위최저순위

---

Programmers/같은 숫자는 싫어/juwon.js

Add: 같은 숫자는 싫어

---

Programmers/문자열 내림차순으로 배치하기/krungy.js

Add: 문자열 내림차순으로 배치하기

---

Programmers/두정수사이의합/juwon.js

Add: 두 정수 사이의 합

---

Programmers/문자열 다루기 기본/krungy.js
Programmers/문자열내p와y의개수/krungy.js

Add: 문자열 다루기 기본, 문자열내p와y의개수

---

Programmers/2016년/juwon.js

Add: 2016년

---

Programmers/부족한 금액 계산하기/krungy.js
Programmers/비밀지도/krungy.js

Add: 부족한 금액 계산하기, 비밀지도

---

Programmers/소수만들기/krungy.js

Add: 소수만들기

---

Programmers/짝수와 홀수/juwon.js

Add: 짝수와 홀수

---

Programmers/부족한 금액 계산하기/juwon.js

Add: 부족한 금액 계산하기

---

Programmers/시저 암호/krungy.js

Add: 시저 암호

---

Programmers/문자열을 정수로 나누기/juwon.js

Add: 문자열을 정수로 나누기

---

Programmers/약수의 합/krungy.js
Programmers/없는숫자더하기/krungy.js
Programmers/예산/krungy.js

Add: 약수의 합, 없는숫자더하기, 예산

---

Programmers/수박수박수박수박수박수?/juwon.js

Add: 수박수박수박수박수박?

---

Programmers/이상한 문자 만들기/krungy.js

Add: 이상한 문자 만들기

---

Programmers/서울에서 김서방 찾기/juwon.js

Add: 서울에서 김서방 찾기

---

Programmers/자릿수 더하기/krungy.js
Programmers/자연수 뒤집어 배열로 만들기/krungy.js

Add: 자릿수 더하기, 자연수 뒤집어 배열로 만들기

---

Programmers/자연수 뒤집어 배열로 만들기/juwon.js

Add: 자연수 뒤집어 배열로 만들기

---

Programmers/정수 내림차순으로 배치하기/krungy.js

Add: 정수 내림차순으로 배치하기

---

Programmers/정수제곱근판별/krungy.js

Add: 정수제곱근판별

---

Programmers/핸드폰번호가리기/juwon.js

Add: 핸드폰 번호 가리기

---

Programmers/제일 작은 수 제거하기/krungy.js

Add: 제일 작은 수 제거하기

---

Programmers/소수만들기/juwon.js

Add: 소수 만들기

---

Programmers/직사각형 별찍기/krungy.js

Add: 직사각형 별찍기

---

Programmers/문자열 다루기 기본/juwon.js

Add: 문자열 다루기 기본

---

Programmers/짝수와 홀수/krungy.js
Programmers/짝지어 제거하기/krungy.js

Add: 짝수와 홀수, 짝지어 제거하기

---

Programmers/최대공약수와 최소공배수/krungy.js

Add: 최대공약수와 최소공배수

---

Programmers/콜라츠 추측/krungy.js

Add: 콜라츠 추측

---

Programmers/K번째수/juwon.js

Add: K번째 수

---

Programmers/자릿수 더하기/juwon.js

Add: 자릿수 더하기

---

Programmers/정수제곱근판별/juwon.js

Add: 정수 제곱근 판별

---

Programmers/하샤드 수/juwon.js

Add: 하샤드 수

---

Programmers/멀쩡한사각형/krungy.js

Add: 멀쩡한사각형

---

Programmers/x만큼 간격이 있는 n개의 숫자/juwon.js

Add: x만큼 간격이 있는 n개의 숫자

---

Programmers/신규 아이디 추천/krungy.js

Add: 신규 아이디 추천

---

Programmers/키패드 누르기/juwon.js

Add: 키패드 누르기

---

Programmers/행렬의 덧셈/krungy.js

Add: 행렬의 덧셈

---

Programmers/소수찾기/juwon.js

Add: 소수 찾기

---

Programmers/숫자의 표현/krungy.js

Add: 숫자의 표현

---

Programmers/이진 변환 반복하기/krungy.js

Add: 이진 변환 반복하기

---

Programmers/최댓값과 최솟값/krungy.js

Add: 최댓값과 최솟값

---

Programmers/최솟값 만들기/krungy.js

Add: 최솟값 만들기

---

Programmers/행렬의 곱셈/krungy.js

Add: 행렬의 곱셈

---

Programmers/H-Index/krungy.js

Add: H-Index

---

Programmers/N개의 최소공배수/krungy.js

Add: N개의 최소공배수

---

Programmers/수박수박수박수박수박수?/krungy.js

Add: 수박수박수박수박수박수?

---

Programmers/문자열을 정수로 바꾸기/krungy.js

Add: 문자열을 정수로 바꾸기

---

Programmers/오픈채팅방/krungy.js

Add: 오픈채팅방

---

Programmers/큰 수 만들기/krungy.js

Add: 큰 수 만들기

---

Programmers/단어 변환/krungy.js

Add: 단어 변환

---

Programmers/가장 큰 정사각형 찾기/krungy.js

Add: 가장 큰 정사각형 찾기

---

Programmers/숫자 게임/krungy.js

Add: 숫자 게임

---

Programmers/N진수 게임/krungy.js

Add: N진수 게임

---

Programmers/최소직사각형/krungy.js

Add: 최소직사각형

---

BOJ/1157_단어 공부/krungy.java

Add: 1157_단어 공부

---

BOJ/1271_엄청난부자2/krungy.js

Add: 1271_엄청난부자2

---

BOJ/1546_평균/krungy.java

Add: 1546_평균
